const express=require('express');const admin=require('firebase-admin');const crypto=require('crypto');const app=express();
const PORT=process.env.PORT||3000,FCM_DEVICE_TOKEN=process.env.FCM_DEVICE_TOKEN,SUPERIOR_PASSWORD=process.env.SUPERIOR_PASSWORD,GOD_PASSWORD=process.env.GOD_PASSWORD;
const COOLDOWN_MS=60000,HISTORY_LIMIT=50,SESSION_MS=12*60*60*1000;let lastSentAt=0,history=[],historyDb=null,lastStatusRequestAt=0;
let deviceStatus={online:false,lastSeen:null,battery:null,charging:null,batteryHealth:null,batteryTemperatureC:null,deviceModel:null,androidVersion:null,appVersion:null,deviceAdmin:null,notificationsEnabled:null,uptimeSeconds:null,screenInteractive:null,ringerMode:null,networkType:null,storageTotalBytes:null,storageFreeBytes:null,ramTotalBytes:null,ramAvailableBytes:null};
let lastDelivery={status:'ready',name:null,command:null,at:null};const sessions=new Map(),loginAttempts=new Map();app.use(express.json({limit:'12kb'}));app.use(express.static(__dirname));
function initFirebase(){if(admin.apps.length)return;const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw Error('FIREBASE_SERVICE_ACCOUNT_JSON is not configured');let s;try{s=JSON.parse(raw)}catch{throw Error('FIREBASE_SERVICE_ACCOUNT_JSON is not valid JSON')}admin.initializeApp({credential:admin.credential.cert(s)})}
function getHistoryDb(){initFirebase();if(!historyDb)historyDb=admin.firestore().collection('summonHistory');return historyDb}
async function loadHistory(){try{const snap=await getHistoryDb().orderBy('atMs','desc').limit(HISTORY_LIMIT).get();history=snap.docs.map(d=>{const x=d.data();return{name:x.name||'',command:x.command||null,status:x.status||'delivered',access:x.access||null,at:new Date(x.atMs||Date.now()).toISOString()}})}catch(e){console.error('HISTORY LOAD ERROR:',e.message)}}
function addHistory(entry){const r={...entry,at:new Date().toISOString()};history.unshift(r);history=history.slice(0,HISTORY_LIMIT);try{getHistoryDb().add({name:r.name||'',command:r.command||null,status:r.status||'delivered',access:r.access||null,atMs:Date.now()}).catch(e=>console.error('HISTORY SAVE ERROR:',e.message))}catch(e){console.error('HISTORY SAVE ERROR:',e.message)}}
async function sendFcm(data){if(!FCM_DEVICE_TOKEN)throw Error('FCM_DEVICE_TOKEN is not configured');initFirebase();const clean={};for(const[k,v]of Object.entries(data))clean[k]=String(v??'').slice(0,500);await admin.messaging().send({token:FCM_DEVICE_TOKEN,data:clean,android:{priority:'high',ttl:60000}})}
function getRemainingCooldown(){return Math.max(0,COOLDOWN_MS-(Date.now()-lastSentAt))}
function getClientIp(req){return String(req.headers['x-forwarded-for']||req.ip||'unknown').split(',')[0].trim()}
function issueSession(role){const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{role,expires:Date.now()+SESSION_MS});return token}
function requireRole(role){return(req,res,next)=>{const token=req.headers.authorization?.startsWith('Bearer ')?req.headers.authorization.slice(7):null,s=token?sessions.get(token):null,allowed=s&&s.expires>=Date.now()&&(role==='superior'?(s.role==='superior'||s.role==='god'):s.role==='god');if(!allowed){if(token&&s?.expires<Date.now())sessions.delete(token);return res.status(401).json({error:role==='god'?'God authentication required.':'Superior authentication required.'})}req.auth=s;req.authToken=token;next()}}
function loginForRole(role,password,req,res){const configured=role==='god'?GOD_PASSWORD:SUPERIOR_PASSWORD;if(!configured)return res.status(503).json({error:role==='god'?'GOD_PASSWORD is not configured on the server.':'SUPERIOR_PASSWORD is not configured on the server.'});const key=role+':'+getClientIp(req),now=Date.now(),recent=(loginAttempts.get(key)||[]).filter(t=>now-t<600000);if(recent.length>=10)return res.status(429).json({error:'Too many login attempts. Try again later.'});recent.push(now);loginAttempts.set(key,recent);const a=Buffer.from(String(password||'')),b=Buffer.from(configured),valid=a.length===b.length&&crypto.timingSafeEqual(a,b);if(!valid)return res.status(401).json({error:'Incorrect '+(role==='god'?'God':'Superior')+' password.'});res.json({ok:true,role,token:issueSession(role),expiresInSeconds:SESSION_MS/1000})}
app.post('/api/superior/login',(req,res)=>loginForRole('superior',req.body?.password,req,res));app.post('/api/god/login',(req,res)=>loginForRole('god',req.body?.password,req,res));
app.post('/api/superior/logout',requireRole('superior'),(req,res)=>{sessions.delete(req.authToken);res.json({ok:true})});app.post('/api/god/logout',requireRole('god'),(req,res)=>{sessions.delete(req.authToken);res.json({ok:true})});
const DEVICE_COMMANDS=new Set(['summon','vibrate','stop_vibration','stop_alarm','notification','wake','volume','volume_up','volume_down','mute','unmute','media_play_pause','media_next','media_previous','media_stop','settings','device_lock']);
app.get('/api/superior/status',requireRole('superior'),(req,res)=>res.json({ok:true,authenticated:true,role:req.auth.role,cooldown:false}));app.get('/api/god/status',requireRole('god'),(req,res)=>res.json({ok:true,authenticated:true,role:'god',controls:[...DEVICE_COMMANDS],cooldown:false}));
app.post('/api/device/status',(req,res)=>{const supplied=String(req.body?.deviceToken||'');if(!FCM_DEVICE_TOKEN||!supplied||supplied!==FCM_DEVICE_TOKEN)return res.status(401).json({error:'Device authentication failed.'});const s=req.body?.status||{},num=v=>Number.isFinite(Number(v))?Number(v):null;deviceStatus={online:true,lastSeen:new Date().toISOString(),battery:num(s.battery),charging:s.charging===true,batteryHealth:String(s.batteryHealth||'unknown').slice(0,40),batteryTemperatureC:num(s.batteryTemperatureC),deviceModel:String(s.deviceModel||'').slice(0,80),androidVersion:String(s.androidVersion||'').slice(0,40),appVersion:String(s.appVersion||'').slice(0,40),deviceAdmin:s.deviceAdmin===true,notificationsEnabled:s.notificationsEnabled!==false,uptimeSeconds:num(s.uptimeSeconds),screenInteractive:s.screenInteractive===true,ringerMode:String(s.ringerMode||'unknown').slice(0,20),networkType:String(s.networkType||'unknown').slice(0,30),storageTotalBytes:num(s.storageTotalBytes),storageFreeBytes:num(s.storageFreeBytes),ramTotalBytes:num(s.ramTotalBytes),ramAvailableBytes:num(s.ramAvailableBytes)};res.json({ok:true,receivedAt:deviceStatus.lastSeen})});
async function getDeviceStatus(req,res){if(Date.now()-lastStatusRequestAt>15000){lastStatusRequestAt=Date.now();try{await sendFcm({type:'status_request',command:'status'})}catch(e){console.error('STATUS REQUEST ERROR:',e.message)}}const stale=deviceStatus.lastSeen?Date.now()-Date.parse(deviceStatus.lastSeen):Infinity;res.json({ok:true,device:{...deviceStatus,online:stale<60000}})}
app.get('/api/superior/device-status',requireRole('superior'),getDeviceStatus);app.get('/api/god/device-status',requireRole('god'),getDeviceStatus);
app.post('/api/buzz',async(req,res)=>{const name=String(req.body?.name||'').trim().slice(0,40),message=String(req.body?.message||'').trim().slice(0,300);if(!name)return res.status(400).json({error:'Your name is required.'});const rem=getRemainingCooldown();if(rem>0)return res.status(429).json({error:'The summon button is on cooldown. Try again in '+Math.ceil(rem/1000)+'s.',waitSeconds:Math.ceil(rem/1000)});try{await sendFcm({name,message,command:'summon',type:'buzz'});lastSentAt=Date.now();lastDelivery={status:'delivered',name,command:'summon',at:new Date().toISOString()};addHistory({name,command:'summon',status:'delivered',access:'public'});res.json({ok:true,mode:'sent',cooldownSeconds:60})}catch(e){console.error('BUZZ ERROR:',e);addHistory({name,command:'summon',status:'failed',access:'public'});res.status(502).json({error:'Could not send buzz: '+e.message})}});
async function sendAuthorizedCommand(req,res,role){const command=String(req.body?.command||'').trim().toLowerCase();if(!DEVICE_COMMANDS.has(command))return res.status(400).json({error:'Unsupported control.'});const fallback=role==='god'?'God':'Superior',name=String(req.body?.name||fallback).trim().slice(0,40)||fallback,message=String(req.body?.message||'').trim().slice(0,300),title=String(req.body?.title||'SISSY BUZZER').trim().slice(0,80),duration=String(Math.max(1,Math.min(300,Number(req.body?.duration)||60))),volume=String(Math.max(0,Math.min(100,Number(req.body?.volume)||100))),pattern=String(req.body?.vibration_pattern||'0,600,250,600,250,1000').slice(0,150);try{await sendFcm({type:'control',command,name,message,title,duration,volume,vibration_pattern:pattern,stream:String(req.body?.stream||'media').slice(0,30),level:String(req.body?.level??'').slice(0,10),target:String(req.body?.target||'').slice(0,40)});lastDelivery={status:'delivered',name,command,at:new Date().toISOString()};addHistory({name,command,status:'delivered',access:role});res.json({ok:true,command,role,cooldown:false})}catch(e){console.error(role.toUpperCase()+' COMMAND ERROR:',e);addHistory({name,command,status:'failed',access:role});res.status(502).json({error:'Could not send command: '+e.message})}}
app.post('/api/superior/command',requireRole('superior'),(req,res)=>sendAuthorizedCommand(req,res,req.auth.role));app.post('/api/god/command',requireRole('god'),(req,res)=>sendAuthorizedCommand(req,res,'god'));
app.get('/api/history',(req,res)=>res.json({history}));app.get('/api/status',(req,res)=>{const rem=getRemainingCooldown(),stale=deviceStatus.lastSeen?Date.now()-Date.parse(deviceStatus.lastSeen):Infinity;res.json({online:true,ready:rem===0,cooldownSeconds:Math.ceil(rem/1000),pending:0,lastDelivery,deviceOnline:stale<60000})});app.get('/health',(req,res)=>res.json({ok:true}));
app.listen(PORT,'0.0.0.0',async()=>{console.log('Sissy Buzzer server listening on port '+PORT);await loadHistory()});